#!/usr/bin/env bash
# Rebuilds the inline icon sprite in site/index.html.
#
# The page draws the same glyphs as the app: Solar's *outline* weight from the
# solar_iconkit package khulla_ui depends on (see AppIcons). Every `#i-<name>`
# referenced from index.html or app.js becomes a <symbol>, so the sprite holds
# exactly what the page uses. Run it after adding or removing an icon:
#
#   site/scripts/icons.sh
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
repo="$(cd "$here/.." && pwd)"

version="$(awk '/^  solar_iconkit:/{found=1} found && /version:/{gsub(/"/,"",$2); print $2; exit}' "$repo/pubspec.lock")"
if [[ -z "$version" ]]; then
  echo "solar_iconkit not found in pubspec.lock — run 'make bootstrap' first." >&2
  exit 1
fi

icons="${PUB_CACHE:-$HOME/.pub-cache}/hosted/pub.dev/solar_iconkit-$version/assets/icons/outline"
if [[ ! -d "$icons" ]]; then
  echo "Icon sources not found at $icons — run 'make bootstrap' first." >&2
  exit 1
fi

python3 - "$here" "$icons" <<'PY'
import pathlib, re, sys

here, icons = map(pathlib.Path, sys.argv[1:])
custom = here / "assets" / "icons"
html_path = here / "index.html"
html = html_path.read_text()
sources = html + (here / "app.js").read_text()

names = sorted(set(re.findall(r"#i-([a-z0-9-]+)", sources)))
symbols, missing = [], []
for name in names:
    svg = icons / f"{name}.svg"
    if not svg.exists():
        svg = custom / f"{name}.svg"
    if not svg.exists():
        missing.append(name)
        continue
    body = re.sub(r"</?svg[^>]*>", "", svg.read_text()).strip()
    symbols.append(f'<symbol id="i-{name}" viewBox="0 0 24 24">{body}</symbol>')

if missing:
    sys.exit("No outline glyph for: " + ", ".join(missing))

sprite = (
    "<!-- icons:start — generated by scripts/icons.sh, do not edit -->\n"
    '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n'
    + "\n".join(symbols)
    + "\n</svg>\n<!-- icons:end -->"
)
html, count = re.subn(r"<!-- icons:start.*?<!-- icons:end -->", lambda _: sprite, html, flags=re.S)
if count != 1:
    sys.exit("index.html needs exactly one icons:start / icons:end marker pair")
html_path.write_text(html)
print(f"{len(symbols)} icons written to {html_path.relative_to(here.parent)}")
PY
