// Copyright (c) 2026 Khulla Digital Library contributors.
// SPDX-License-Identifier: MIT

// The one place the app version is read from `pubspec.yaml`, so the number on
// the download, the number in the tag and the number on the screen cannot
// disagree.
//
// `pubspec.yaml` is the source of truth because it is the one copy the build
// tools already read: it becomes the Windows file version, the Android
// versionCode, and the version CI releases at.
//
// Usage:
//   dart tools/version.dart            0.1.0        the released version
//   dart tools/version.dart --full     0.1.0+1      with the build number
//   dart tools/version.dart --build    1            the build number alone
//   dart tools/version.dart --write                 writes lib/gen/app_version.dart
//
// Deliberately imports nothing but dart:io, so CI can run it with a bare Dart
// SDK — no pub get, no Flutter, no code generation first.
import 'dart:io';

/// Where `--write` puts the generated constants.
///
/// `lib/gen/` is gitignored: a committed copy could sit at 0.1.0 while the
/// pubspec said 1.0.0, which is the failure this script exists to remove.
const String _outputPath = 'lib/gen/app_version.dart';

/// `1.2.3` or `1.2.3+4`, and nothing else — a version this cannot parse is a
/// version CI would release under the wrong name.
final RegExp _versionLine = RegExp(
  r'^version:\s*(\d+\.\d+\.\d+)(?:\+(\d+))?\s*$',
);

void main(List<String> args) {
  final pubspec = File('pubspec.yaml');
  if (!pubspec.existsSync()) {
    _fail('No pubspec.yaml here. Run this from the repository root.');
  }

  final (version, build) = _parse(pubspec.readAsLinesSync());

  switch (args.isEmpty ? '' : args.first) {
    case '':
      stdout.writeln(version);
    case '--full':
      stdout.writeln(build == null ? version : '$version+$build');
    case '--build':
      stdout.writeln(build ?? '');
    case '--write':
      _write(version, build);
    default:
      _fail(
        'Unknown option "${args.first}". '
        'Expected one of: --full, --build, --write.',
      );
  }
}

/// The `version:` field, split into the version and its build number.
(String, int?) _parse(List<String> lines) {
  for (final line in lines) {
    final match = _versionLine.firstMatch(line);
    if (match != null) {
      final build = match.group(2);
      return (match.group(1)!, build == null ? null : int.parse(build));
    }
  }

  _fail(
    'No `version: <major>.<minor>.<patch>[+<build>]` line in pubspec.yaml. '
    'Every release is named after that line, so it has to be readable.',
  );
}

void _write(String version, int? build) {
  File(_outputPath)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync('''
// Copyright (c) 2026 Khulla Digital Library contributors.
// SPDX-License-Identifier: MIT

// GENERATED BY tools/version.dart — DO NOT MODIFY BY HAND.
// Regenerate with `make build`. The source is `version:` in pubspec.yaml.

/// The released version, `1.2.3`. What a release is tagged and named after.
const String kAppVersion = '$version';

/// The build number after the `+` in pubspec.yaml, and Android's versionCode.
///
/// Null when the pubspec omits it. It has to climb on every Android release —
/// the Play Store and the sideload installer both refuse an APK whose build
/// number did not increase.
const int? kAppBuildNumber = ${build ?? 'null'};

/// Version and build together, `1.2.3+4`. Use this where a bug report has to
/// name an exact build; [kAppVersion] is what a person reads.
const String kAppFullVersion = '${build == null ? version : '$version+$build'}';
''');

  stdout.writeln(
    'Wrote $_outputPath at ${build == null ? version : '$version+$build'}.',
  );
}

Never _fail(String message) {
  stderr.writeln('tools/version.dart: $message');
  exit(1);
}
