#!/usr/bin/env sh

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

if ! echo "$COMMIT_MSG" | grep -qE '^(feat|fix|chore|refactor|sync|ci)(\([a-zA-Z0-9_-]+\))?: .+'; then
  echo "Error: Commit message does not follow the standard convention."
  echo "Use: type(scope): message"
  echo "Types: feat, fix, chore, refactor, sync, ci"
  exit 1
fi

exit 0
